# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BroncoHack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BroncoHack
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'

  pod 'SkyFloatingLabelTextField', '~> 2.0.0'

  target 'BroncoHackTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BroncoHackUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
